### ISSUE TITLE
Add date picker

### ISSUE THREAD

**Issue by lklyne** [nasa-jpl/stellar#98]
Add a date picker to support easy date selection. This date picker should account for unique time considerations found in spacecraft operations.
- Day of year display
- Multiple time zones + formats (UTC, LMST, etc)
- Manual input

Being built on top of [React DayPicker](https://www.google.com/search?q=react+day+picker&sourceid=chrome&ie=UTF-8)

Ideas:
- Add min + max validation props to support two inputs for ranges and specific validation needs.
- Time conversion
- Prettier formatting for UTC times

**Comment by AaronPlave** [comment]
@lklyne maybe move this to react-stellar?

**Comment by lklyne** [comment]
Going to recreate this in react-stellar
